services:
  api:
    build: 
      context: .
      target: debug
    networks:
      - npmext	
    ports:
      - "5000:5000"
      - "5678:5678"
    volumes:
      - .:/app
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
networks:
  npmext:
    external: true
    name: npmnetwork
